# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# Don't add an extra indent level to methods after a `private`/`protected` modifier.
# (Omakase defaults this to `indented_internal_methods`.)
Layout/IndentationConsistency:
  EnforcedStyle: normal
